language: java
sudo: true
dist: trusty
jdk: oraclejdk8
script:
- mvn clean install -B
cache:
  directories:
    - $HOME/.m2
before_install:
  - chmod a+x ./mvnw
after_success:
  - bash <(curl -s https://codecov.io/bash)